from reportlab.lib.pagesizes import letter, A4
from reportlab.lib.styles import getSampleStyleSheet, ParagraphStyle
from reportlab.lib.units import inch
from reportlab.platypus import SimpleDocTemplate, Paragraph, Spacer, Table, TableStyle, PageBreak
from reportlab.lib import colors
from reportlab.lib.enums import TA_CENTER, TA_LEFT
from io import BytesIO
from datetime import datetime

def generate_roadmap_pdf(roadmap, progress_data=None):
    """
    Generate a PDF for a roadmap with professional formatting
    """
    buffer = BytesIO()
    doc = SimpleDocTemplate(buffer, pagesize=letter, topMargin=0.5*inch, bottomMargin=0.5*inch)
    
    # Container for PDF elements
    elements = []
    
    # Styles
    styles = getSampleStyleSheet()
    
    # Custom styles
    title_style = ParagraphStyle(
        'CustomTitle',
        parent=styles['Heading1'],
        fontSize=24,
        textColor=colors.HexColor('#1e40af'),
        spaceAfter=12,
        alignment=TA_CENTER,
        fontName='Helvetica-Bold'
    )
    
    subtitle_style = ParagraphStyle(
        'CustomSubtitle',
        parent=styles['Normal'],
        fontSize=12,
        textColor=colors.HexColor('#6b7280'),
        spaceAfter=20,
        alignment=TA_CENTER
    )
    
    week_title_style = ParagraphStyle(
        'WeekTitle',
        parent=styles['Heading2'],
        fontSize=16,
        textColor=colors.HexColor('#2563eb'),
        spaceAfter=8,
        fontName='Helvetica-Bold'
    )
    
    section_style = ParagraphStyle(
        'Section',
        parent=styles['Normal'],
        fontSize=11,
        textColor=colors.HexColor('#374151'),
        spaceAfter=6,
        fontName='Helvetica-Bold'
    )
    
    body_style = ParagraphStyle(
        'Body',
        parent=styles['Normal'],
        fontSize=10,
        textColor=colors.HexColor('#4b5563'),
        spaceAfter=4,
        leftIndent=20
    )
    
    # Header
    elements.append(Paragraph("SkillSprint AI", title_style))
    elements.append(Paragraph("Your Personalized Learning Roadmap", subtitle_style))
    elements.append(Spacer(1, 0.2*inch))
    
    # Roadmap Info
    info_data = [
        ['Goal:', roadmap.goal],
        ['Duration:', f'{roadmap.duration_weeks} weeks'],
        ['Created:', roadmap.created_at.strftime('%B %d, %Y')],
    ]
    
    if progress_data:
        info_data.append(['Progress:', f'{progress_data.completed_weeks}/{progress_data.total_weeks} weeks ({progress_data.progress_percent}%)'])
    
    info_table = Table(info_data, colWidths=[1.5*inch, 5*inch])
    info_table.setStyle(TableStyle([
        ('BACKGROUND', (0, 0), (0, -1), colors.HexColor('#eff6ff')),
        ('TEXTCOLOR', (0, 0), (0, -1), colors.HexColor('#1e40af')),
        ('FONTNAME', (0, 0), (0, -1), 'Helvetica-Bold'),
        ('FONTSIZE', (0, 0), (-1, -1), 10),
        ('PADDING', (0, 0), (-1, -1), 8),
        ('GRID', (0, 0), (-1, -1), 0.5, colors.HexColor('#e5e7eb')),
        ('VALIGN', (0, 0), (-1, -1), 'TOP'),
    ]))
    
    elements.append(info_table)
    elements.append(Spacer(1, 0.3*inch))
    
    # Week-by-week breakdown
    elements.append(Paragraph("Weekly Learning Plan", week_title_style))
    elements.append(Spacer(1, 0.1*inch))
    
    for week in roadmap.week_plans:
        # Week header
        week_header = f"Week {week.week_number}: {week.focus_title}"
        elements.append(Paragraph(week_header, week_title_style))
        elements.append(Spacer(1, 0.05*inch))
        
        # Topics
        elements.append(Paragraph("📚 Topics to Learn:", section_style))
        for topic in week.topics_json:
            elements.append(Paragraph(f"• {topic}", body_style))
        elements.append(Spacer(1, 0.1*inch))
        
        # Practice Tasks
        elements.append(Paragraph("✅ Practice Tasks:", section_style))
        for task in week.tasks_json:
            elements.append(Paragraph(f"• {task}", body_style))
        elements.append(Spacer(1, 0.1*inch))
        
        # Target Problems
        elements.append(Paragraph(f"🎯 Target: {week.target_problems} problems/exercises", section_style))
        elements.append(Spacer(1, 0.2*inch))
        
        # Add separator line
        line_table = Table([['']], colWidths=[6.5*inch])
        line_table.setStyle(TableStyle([
            ('LINEABOVE', (0, 0), (-1, 0), 1, colors.HexColor('#e5e7eb')),
        ]))
        elements.append(line_table)
        elements.append(Spacer(1, 0.2*inch))
    
    # Footer
    elements.append(Spacer(1, 0.3*inch))
    footer_style = ParagraphStyle(
        'Footer',
        parent=styles['Normal'],
        fontSize=9,
        textColor=colors.HexColor('#9ca3af'),
        alignment=TA_CENTER
    )
    elements.append(Paragraph(f"Generated by SkillSprint AI on {datetime.now().strftime('%B %d, %Y')}", footer_style))
    elements.append(Paragraph("Your AI-Powered Learning Companion", footer_style))
    
    # Build PDF
    doc.build(elements)
    buffer.seek(0)
    return buffer
